#!/bin/sh
xrandr \
    --output DisplayPort-1-1 \
        --mode 1920x1080 \
        --pos 0x0 \
        --rotate left \
    --output DP-1 \
        --primary \
        --mode 1920x1080 \
        --pos 1080x0 \
        --rotate normal \
    --output VGA-1 \
        --off \
    --output HDMI-1
        --off \
    --output DVI-1-0 \
        --off
