#!/bin/sh
xrandr \
    --output DP-1-2 \
        --off \
    --output DP-1 \
        --off

xrandr \
    --output DP-1-2 \
        --mode 1920x1080 \
        --pos 0x0 \
        --rotate left \
    --output DP-1 \
        --primary \
        --mode 1920x1080 \
        --pos 1080x0 \
        --rotate normal
