#!/bin/bash

function cwd_guard() {
    local _SCRIPT_LOCATION="$0"
    local _ABSOLUTE_LOCATION=$(dirname "${_SCRIPT_LOCATION}")
    cd "${_ABSOLUTE_LOCATION}"
}
cwd_guard

function kill_exist() {
  for pid in $(pgrep polybar -al | grep 'polybar --reload polybar' | cut -d' ' -f1)
  do
    kill $pid
  done
}

declare -A POLYBAR_PIDS

function start_polybars() {
  export TOOLS="$PWD"
  # run on primary monitor
  for monitor in $(polybar -m | grep primary | cut -d":" -f1)
  do
    MONITOR=$monitor polybar --reload polybar &
    POLYBAR_PIDS[$monitor]=$!
  done
  # run on non-primary monitor
  for monitor in $(polybar -m | grep -v primary | cut -d":" -f1)
  do
    MONITOR=$monitor TRAY_POSITION=" " polybar --reload polybar &
    POLYBAR_PIDS[$monitor]=$!
  done
}

function kill_polybars() {
  for monitor in ${POLYBAR_PIDS[@]}
  do
    kill $monitor
  done
}

trap "kill_polybars; exit 0" HUP INT PIPE QUIT TERM
kill_exist
start_polybars
wait