#!/bin/bash

function cwd_guard() {
    local _SCRIPT_LOCATION="$0"
    local _ABSOLUTE_LOCATION=$(dirname "${_SCRIPT_LOCATION}")
    cd "${_ABSOLUTE_LOCATION}"
}
cwd_guard

V2API="127.0.0.1:10085"
while true
do
    if pgrep v2ray >/dev/null 2>&1
    then
        v2ctl api "--server=$V2API" StatsService.QueryStats 'reset: true' | \
            grep -v 'api' | \
            grep -A1 'name: ' | \
            sed -e '/--/d' -e 'N;s/\n/ /' -e 's/>$/  value: 0/' | \
            sed -e 's/^  name: ".*>>>\([a-z]\+\)" *value: \([0-9]\+\)$/\1 \2/' | \
            awk '{
                if ($1 == "uplink") {
                    uplink += $2
                } else {
                    downlink += $2
                }
            }
            END {
                printf(" %d  %d\n", uplink, downlink)
            }' | \
            numfmt --field=2,4 --suffix=B --to=iec --padding=1
    else
        echo "ﳼ "
    fi
    sleep 1
done
