#!/bin/bash

declare -A ACTIONS
ACTIONS=(
    [poweroff]="systemctl poweroff"
    [sleep]="systemctl hybrid-sleep"
    [hibernate]="systemctl hibernate"
    [reboot]="systemctl reboot"
    [logout]="i3-msg exit"
)

function get_action() {
    echo ${!ACTIONS[@]} | tr ' ' '\n' | rofi -p Power -dmenu
}

function main() {
    local action=$(get_action)
    if [ -n "$action" ]
    then
        ${ACTIONS[$action]}
    fi
}

main
