#!/bin/bash

ACTION=$(echo -ne "poweroff
sleep
reboot
logout
lock" | rofi -p "Power" -width -20 -font "Microsoft Yahei 25" -dmenu -p "Power" -l 4 )

case $ACTION in
    poweroff)
        systemctl poweroff
        ;;
    sleep)
        systemctl hybrid-sleep
        ;;
    reboot)
        systemctl reboot
        ;;
    logout)
        i3-msg exit
        ;;
    *)
        ;;
esac