#!/bin/bash

if which sslocal >/dev/null
then
    SSLOCAL=sslocal
elif which ss-local >/dev/null
then
    SSLOCAL=ss-local
else
    exit 1
fi

SSHOME=$HOME/.cache/shadowsocks/
mkdir -p $SSHOME

DIR=$(dirname $0)
CONFIGS=$DIR/../configs/shadowsocks/gui-config.json
CONFIG=$SSHOME/config.json
PID=$SSHOME/ss.pid
LOG=$SSHOME/ss.log

server=$(
    jq -r '.configs[] | 
        [
            .server,
            if .remarks != "" then
                " (" + .remarks + ")"
            else
                ""
            end
        ] | add' $CONFIGS |
        rofi -p "Shadowsocks" -dmenu -no-custom
)

server=${server% *}

if [ -z "$server" ]
then
    exit 1
fi

jq '.configs[] | select(.server == "'$server'")' $CONFIGS > $CONFIG

$SSLOCAL -d restart -c $CONFIG --pid-file=$PID --log-file=$LOG -vv