#!/bin/sh

function cwd_guard() {
    local _SCRIPT_LOCATION="$0"
    local _ABSOLUTE_LOCATION=$(dirname "${_SCRIPT_LOCATION}")
    cd "${_ABSOLUTE_LOCATION}"
}
cwd_guard

./canvas/canvas -S 1920x1080 -b -a -R